services:
  frontend:
    image: lekky/devops-demo-frontend:latest
    restart: always
    container_name: frontend-c
    ports:
      - "8080:80"    
    networks:
      - devops-demo-network
    
  backend:
    image: lekky/devops-demo-backend:latest
    restart: always
    container_name: backend-c
    environment:
      - DATABASE_URL=$DATABASE_URL
      - PORT=$PORT      
    networks:
      - devops-demo-network   

networks:
  devops-demo-network:
    driver: bridge