services:
  postgres:
    image: postgres:17.4-alpine3.21
    container_name: pg-c
    restart: always    
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - "5432:5432"
