name: Test and Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  setup:
    name: Setup Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'          

      - name: Install pnpm
        run: npm install -g pnpm
      
      - name: Debug PNPM
        run: pnpm --version

      - name: Install Dependencies for Frontend
        working-directory: ./frontend
        run: pnpm install

      - name: Install Dependencies for Backend
        working-directory: ./backend
        run: pnpm install

  